server:
  port: 8080
  context-path: /rabbitmq


spring:
  rabbitmq:
    host: dev.tss.com
    port: 5672
    username: admin
    password: njittss
    # 开启发送确认
    #publisher-confirms: true
    # 开启发送失败退回，或者通过rabbitTemplate.setMandatory(true);设置
    #publisher-returns: true

rabbitmq:
  test:
    mandatory:
      exchangeName: direct.exchange.test.mandatory
      queueName: direct.queue.test.mandatory
      routingKey: direct.routing-key.test.mandatory
    ae:
      normalExchange: direct.exchange.test.ae-normal
      normalQueue: direct.queue.test.ae-normal
      normalRoutingKey: direct.routing-key.test.ae-normal
      aeExchange: fanout.exchange.test.ae
      aeQueue: fanout.queue.test.ae
    ttl:
      msgQueueTtlExchange: direct.exchange.test.ttl.msg-queue
      msgQueue: direct.queue.test.ttl.msg-queue
      msgQueueRoutingKey: direct.routing-key.test.ttl.msg-queue
      singleMsgTtlExchange: direct.exchange.test.ttl.msg-single
      singleMsgQueue: direct.queue.test.ttl.msg-single
      singleMsgRoutingKey: direct.routing-key.test.ttl.msg-single
      queueTtlExchange: direct.exchange.test.ttl.queue
      queue: direct.queue.test.ttl.queue
      queueRoutingKey: direct.routing-key.test.ttl.queue
    dlx:
      normalExchange: direct.exchange.test.dlx-normal
      normalQueue: direct.queue.test.dlx-normal
      normalRoutingKey: direct.routing-key.test.dlx-normal
      dlxExchange: direct.exchange.test.dlx
      dlxQueue: direct.queue.test.dlx
      dlxRoutingKey: direct.routing-key.test.dlx
    priority:
      exchange: direct.exchange.test.priority
      queue: direct.queue.test.priority
      routingKey: direct.routing-key.test.priority

